//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Booking_Id { get; set; }
        public Nullable<int> Hotel_Id { get; set; }
        public Nullable<int> Room_Id { get; set; }
        public string StatusOfBooking { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string IsActive { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Room Room { get; set; }
    }
}
