//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    using System.Web;
    using Aspose.Slides;
    using SmartFormat.Core.Parsing;

    public partial class product
    {

        public int Product_id { get; set; }
        [DisplayName("Name")]
        [Required]
        public string Product_name { get; set; }
        [DisplayName("Category")]
        [Required]
        public string Product_Category { get; set; }
      
        [DisplayName("Price")]
        [Required]
        public decimal Product_Price { get; set; }
      
        [DisplayName("Quantity")]
        [Required]
        public int Product_Quantity { get; set; }
        [Required]
        [DisplayName("Short-Description")]

        public string Short_Description { get; set; }
        [Required]
        [DisplayName("Long-Description")]
        [DataType(DataType.MultilineText)]
        public string Long_Description { get; set; }
        [DisplayName("Small Image")]
        public string Small_Image_path { get; set; }
        [DisplayName("Large Image")]
         public string Large_Image_path { get; set; }

        public HttpPostedFileBase SImageFile { get; set; }

        public HttpPostedFileBase LImageFile { get; set; }


    }
}
